import type { Question } from './questions'

const items: Omit<Question, 'id' | 'cardId'>[] = [
  {
    chapter: 7,
    prompt: 'A global service uses Anycast and latency-based DNS. What do these features still not guarantee?',
    options: ['A choice of network destination', 'The ability to cache a DNS answer', 'That every region has current data and may safely accept the same booking', 'Different routing choices for different networks'], correct: 2,
    explanation: 'Anycast influences the network route to a shared address, while a DNS policy chooses an address using available location or latency information. Neither copies the latest booking data or gives every region safe write ownership. Cached answers and existing connections also delay traffic changes. A regional recovery plan must separately check capacity, data lag, credentials, and which participant may accept writes.',
    term: 'Anycast versus GeoDNS',
    definition: 'Anycast advertises one address from several locations and lets routing choose a path. GeoDNS changes DNS answers using estimated location. Latency-based DNS uses suitable latency information. None automatically provides current business data, instant failover, or resource-level permission.',
  },
  {
    chapter: 14,
    prompt: 'An API generates product category pages dynamically. Can a CDN ever cache those responses?',
    options: ['Yes, when reuse, cache keys, freshness, and access rules permit it', 'No, only image files can be cached', 'Yes, all responses can share one key even when private', 'Only if the origin database is removed'], correct: 0,
    explanation: 'Dynamic describes how a response is produced, not whether its result can be reused. A public category response may be shared for a defined time using the right language, currency, and other key inputs. Private or freshness-critical responses need different rules. An edge worker may apply supported logic, but it does not make temporary memory durable or replace the official authorization and data checks.',
    term: 'Dynamic edge caching',
    definition: 'A generated page or API response can be cached when its meaning and permissions allow reuse. Choose keys and lifetime deliberately. Edge workers add nearby computation, but a distant database and private business state still have their own latency and correctness rules.',
  },
  {
    chapter: 11,
    prompt: 'Why is a B+ Tree useful for reading a sorted range of order records?',
    options: ['It makes every write free', 'Internal pages locate a leaf, then ordered leaves support the range read', 'It removes the cost of returning a million rows', 'It automatically authorizes every matching order'], correct: 1,
    explanation: 'A B+ Tree uses many separator keys per internal page to narrow the search with relatively few page reads. Its ordered leaf level then supports continuing through a range. The exact storage layout depends on the engine. Output size still matters, and maintaining pages and indexes adds write cost. Choose the composite key order from the query rather than assuming one index speeds up every access pattern.',
    term: 'B+ Tree range access',
    definition: 'Internal pages guide a lookup to a starting leaf, and the ordered leaf level helps scan nearby keys. This supports suitable range queries. It still requires storage, page maintenance, and work proportional to the result that the query actually returns.',
  },
  {
    chapter: 12,
    prompt: 'With three fixed replicas, reads and writes each require two replies. What does R + W > N establish by itself?',
    options: ['Every possible history is automatically linearizable', 'Concurrent writes cannot occur', 'All acknowledgements necessarily mean a durable disk flush', 'The chosen read and acknowledged-write sets must overlap'], correct: 3,
    explanation: 'Two members of a fixed set of three must overlap another set of two. That means a later read can encounter a replica that acknowledged the write. The inequality does not specify version selection, concurrent-write handling, membership changes, sloppy quorums, or acknowledgement durability. Those protocol rules determine the actual guarantee. Overlap is one ingredient, not a complete proof of strong consistency.',
    term: 'Quorum overlap',
    definition: 'For a fixed replica set, R plus W greater than N ensures that the selected read and acknowledged-write sets intersect. A correct consistency claim also needs the database rules for versions, concurrent changes, failures, membership, and the meaning of an acknowledgement.',
  },
  {
    chapter: 13,
    prompt: 'A popular cached calculation takes a long time to rebuild. What does XFetch try to improve?',
    options: ['The chance of refreshing before many callers all see the same expiry', 'The durability of every database transaction', 'A guarantee that exactly one refresher runs under every failure', 'The ability to ignore the response freshness policy'], correct: 0,
    explanation: 'XFetch uses remaining lifetime, an estimate of rebuild duration, and randomness to decide when a request should refresh early. This reduces the synchronized pressure caused by waiting for every caller to see one expiry instant. Several refreshes can still overlap, and low traffic may trigger none before expiry. Combine it with appropriate loading limits, coordination where needed, and an honest freshness policy.',
    term: 'XFetch early refresh',
    definition: 'A probabilistic approach that may refresh a cache entry before expiry, using randomness and the cost of regeneration. It can reduce synchronized misses, but it does not guarantee a single worker, repair a failed cache, or make unlimited stale serving acceptable.',
  },
  {
    chapter: 13,
    prompt: 'Debezium sends committed price changes to a cache invalidator. Why can customers still briefly see an old price?',
    options: ['CDC prevents the database from committing', 'All cache keys become automatically private', 'The pipeline is asynchronous and old reads can still refill the cache', 'The connector makes all systems one local transaction'], correct: 2,
    explanation: 'The database commit, change capture, event delivery, and cache update happen in separate steps. A connector or consumer can lag, and a reader may refill an old value after invalidation. Use version-aware publication, appropriate read rules, checkpoints, and recovery. CDC helps avoid forgotten updates but does not erase propagation delay. Checkout still needs an official rule for the price the customer accepts.',
    term: 'CDC-driven cache repair',
    definition: 'A pipeline that follows committed database changes and updates or invalidates a cache. It improves coverage across writers, but remains asynchronous. Versions, deletion handling, checkpoints, a rebuild path, and a measured freshness policy are still required for a reliable result.',
  },
  {
    chapter: 20,
    prompt: 'An SQS worker receives a job and then crashes before deleting it. Which mechanism makes the job eligible again?',
    options: ['An unchanged DNS TTL', 'Expiry of the message visibility timeout', 'The producer choosing a larger image size', 'FIFO send deduplication rolling back the worker'], correct: 1,
    explanation: 'Visibility timeout temporarily hides received work. If the worker does not delete it before the timeout ends, another attempt can become eligible. Initial queue delay controls a different stage, before first delivery. FIFO send deduplication does not roll back an external effect the first worker already made. Use stable operation identity and safe result handling so another attempt recovers rather than repeats an unwanted effect.',
    term: 'SQS delay versus visibility',
    definition: 'Initial delay postpones when a new message can first be received. Visibility timeout hides a message after a consumer receives it. Expiry allows recovery of unfinished delivery, but repeated attempts still need safe business processing and an appropriate redrive policy.',
  },
  {
    chapter: 22,
    prompt: 'A window contains 100 normal attempts. Retries may be at most 10% of total outgoing attempts, including retries. What is the largest whole-number retry count?',
    options: ['10 is the only possible interpretation', '12', '100', '11'], correct: 3,
    explanation: 'The rule is retries divided by normal attempts plus retries, not retries divided only by normal attempts. Eleven retries out of 111 total attempts are just under 10%; twelve out of 112 exceed it. A separate policy of ten retries per hundred normal calls uses another denominator. Define the scope, window, and shared accounting, and include nested SDK attempts in the budget.',
    term: 'Retry traffic budget',
    definition: 'A limit on the combined retry traffic sent to a dependency, separate from one operation\'s attempt count. State whether the percentage uses normal calls or all calls as its denominator, and whether accounting is exact or an explicitly allowed approximation.',
  },
  {
    chapter: 15,
    prompt: 'A three-voter Raft cluster has only one reachable node. Can it safely keep committing ordinary writes by calling that node the leader?',
    options: ['No; naming a leader does not replace the required quorum and commit rules', 'Yes; a local disk always represents the whole committed history', 'Yes; timeouts prove the other nodes have no state', 'Yes; every reachable node is a majority'], correct: 0,
    explanation: 'A single member is not a majority of three. Raft protects agreed history through elections, terms, log rules, and valid commit decisions, not merely a leader label. A lone node may lack important information and cannot promise ordinary quorum-backed commits. Restore enough valid participants or follow an explicit recovery procedure with understood consequences rather than silently discarding the original guarantee.',
    term: 'Consensus safety and progress',
    definition: 'Safety prevents conflicting committed decisions under the protocol\'s assumptions. Progress requires suitable communication and enough valid participants. A consensus system can preserve safety by refusing writes when quorum is lost; adding a leader label does not recreate the missing evidence.',
  },
  {
    chapter: 15,
    prompt: 'A Paxos proposer obtains promises for a higher ballot. Can it ignore all previously accepted values and choose any new value?',
    options: ['Yes, higher ballot numbers erase accepted history', 'No, it must follow the prior-value selection rule from the prepare replies', 'Only if the new value is smaller', 'Yes, because prepare is the final business commit'], correct: 1,
    explanation: 'Prepare replies report prior accepted proposals. When such values are relevant, the proposer must use the value attached to the highest-numbered accepted proposal in its required replies. These rules and quorum intersection protect already chosen decisions across new attempts. A higher ballot grants no permission to forget history. Practical protocols also need durable state and mechanisms that help make progress despite competing proposers.',
    term: 'Paxos and ZAB',
    definition: 'Paxos protects agreement on a chosen value, with Multi-Paxos extending agreement to a sequence. ZAB protects ZooKeeper\'s ordered changes across leadership epochs. Both require complete protocol rules; neither makes every external application effect part of its internal agreement automatically.',
  },
  {
    chapter: 15,
    prompt: 'Worker A resumes after its lease expires and worker B publishes a newer result. What protects the resource from A\'s delayed write?',
    options: ['A still having a local boolean set to true', 'Using the same random unlock value forever', 'A resource-side fencing or version check that rejects the older owner', 'A longer log message'], correct: 2,
    explanation: 'A lease expiry allows another owner to make progress, but it does not stop the old process from resuming. The resource must reject stale work using a suitable increasing ownership token or protected version condition. A random unlock value solves a different problem: avoiding deletion of someone else\'s lock. If the external resource cannot enforce the required protection, state the remaining limitation and use supported recovery mechanisms.',
    term: 'Fencing a stale worker',
    definition: 'The protected resource checks ownership generations or another suitable version before accepting a change. Once a newer owner is accepted, an older delayed write is rejected. The check must happen with the actual effect, not only in the worker\'s local memory.',
  },
  {
    chapter: 15,
    prompt: 'A service adopts UUIDv7 for order identities. Which claim would still be unsafe?',
    options: ['The format includes time-oriented information', 'A maintained library should generate the IDs', 'Index locality depends on the workload and engine', 'Sorting all IDs proves the exact global order of business commits'], correct: 3,
    explanation: 'UUIDv7 provides a time-oriented layout, but clocks, concurrent generation, and the delay between generating and committing an order still matter. It does not establish one exact business commit order across machines. The same distinction applies to Snowflake-style IDs. Choose identity generation for its real uniqueness and operating requirements, and protect reservations, permissions, and business ordering with their own suitable mechanisms.',
    term: 'ID order versus business order',
    definition: 'An ID may include a timestamp or sequence without proving the exact order of accepted business changes. Generation and commit are separate events. Snowflake-style IDs, UUIDs, and ticket services still need appropriate uniqueness, clock, ownership, and recovery rules.',
  },
  {
    chapter: 23,
    prompt: 'A 2PC participant voted yes but cannot learn the final decision. Why can it not simply abort when a timer expires?',
    options: ['Another participant may already have committed the coordinator\'s recorded decision', 'Prepared means the transaction was definitely rejected', 'A timer automatically rolls back every other database', 'The participant never saved any prepared state'], correct: 0,
    explanation: 'The coordinator may have durably recorded commit and delivered it to another participant before communication failed. If this prepared participant independently aborts, the transaction can split between committed and aborted results. It must learn and follow the supported final decision through recovery. This uncertainty explains 2PC blocking and the cost of holding prepared resources; it is not fixed by inventing an answer locally.',
    term: 'Two-phase commit recovery',
    definition: 'Participants first prepare, then follow the durable commit or abort decision. A participant that voted yes may need to wait when that decision is unknown. Recovery must preserve the shared result, and unrelated external APIs are not automatically transaction participants.',
  },
  {
    chapter: 23,
    prompt: 'Does adding the pre-commit phase in 3PC guarantee non-blocking atomic commit under every arbitrary network partition?',
    options: ['Yes, any extra message removes uncertainty', 'Yes, local clocks always reveal the other side\'s decision', 'No; its non-blocking reasoning depends on a restricted failure and timing model', 'Yes, it automatically includes every HTTP provider'], correct: 2,
    explanation: 'Classic 3PC arguments depend on timing and failure assumptions that an arbitrary partition may violate. The extra phase provides more state for certain recovery cases, but it does not give isolated participants complete knowledge of one another. Explain the actual guarantees of a supported implementation. A saga provides a different model with explicit intermediate states and compensation, not the same instantaneous atomicity.',
    term: 'Three-phase commit assumptions',
    definition: '3PC adds a pre-commit stage between initial agreement and final commit. Its recovery benefits depend on the supported timing and failure model. It does not make arbitrary partitions harmless or turn independent HTTP side effects into one atomic transaction.',
  },
  {
    chapter: 26,
    prompt: 'Two servers report their own p99 latency. Why should you not simply average those values to obtain the service\'s p99?',
    options: ['Percentiles never contain useful information', 'The servers can have different request counts and distributions', 'A gauge is always a complete latency distribution', 'Averages automatically give a stricter guarantee'], correct: 1,
    explanation: 'Each p99 summarizes a different distribution and possibly a very different number of requests. Averaging those two summary values does not reconstruct the combined distribution. Combine compatible histogram data or another supported distribution representation, then estimate the service percentile over the same window and operation. Keep label counts manageable, and use traces and logs to investigate why the slow observations occurred.',
    term: 'Histograms and fleet percentiles',
    definition: 'Histograms retain distribution information so suitable measurements can be combined across instances before estimating percentiles. Bucket design affects precision. A counter counts events, a gauge shows a current level, and neither automatically replaces the distribution needed for a service-wide p99.',
  },
  {
    chapter: 27,
    prompt: 'A reporting service presents a valid client certificate over mTLS. What must the invoice API still check?',
    options: ['Only whether the source network is private', 'Nothing; all internal services may read every invoice', 'Whether the certificate filename contains the tenant name', 'Permission for the requested action and tenant-specific invoice'], correct: 3,
    explanation: 'Mutual TLS helps establish workload identities and protects the connection. It does not grant that workload permission to perform every business action or access every tenant. The API still checks the relevant service and resource policy, including cached responses and file downloads. Certificate issuance, renewal, expiry, and trust changes also need an operating plan. A secure connection can still carry a request that must be refused.',
    term: 'Zero trust with mTLS',
    definition: 'Do not grant broad permission merely because a caller is internal. Mutual TLS verifies configured workload identities and protects transport, while authorization checks the requested action and resource. The same scope must hold through caches, storage, downloads, and background jobs.',
  },
  {
    chapter: 11,
    prompt: 'An order commit was acknowledged after the required WAL records became durable. The process crashes before modified data pages are flushed. What should recovery use?',
    options: ['The client browser cache', 'The durable log and the engine recovery protocol', 'An assumption that every unflushed page means a lost order', 'A fresh order ID that repeats the purchase'], correct: 1,
    explanation: 'Under the stated durability policy, the required log records are made durable before acknowledgement. If that storage survives, the engine can recover committed changes even when data pages were not yet flushed. This does not cover destruction of the same storage or unsafe acknowledgement settings. A client with an uncertain result should look up or safely retry the original operation rather than create a duplicate.',
    term: 'Write-ahead logging',
    definition: 'Recovery information is logged before affected data pages become durable. The configured commit policy determines when success may be acknowledged. WAL supports crash recovery but does not by itself provide independent backups, geographic replication, or survival of destroyed storage.',
  },
  {
    chapter: 11,
    prompt: 'An LSM-backed store accepts writes quickly at first, then periodically stalls as files accumulate. What is the most useful investigation?',
    options: ['Only the browser font size', 'Whether every request uses GraphQL', 'Compaction debt, flush pressure, and storage bandwidth', 'Whether more API replicas can bypass the same disk'], correct: 2,
    explanation: 'LSM writes create immutable files that need merging over time. Compaction can compete with reads and writes for disk bandwidth, CPU, and temporary space. A short benchmark may finish before the steady-state cost appears. Inspect compaction debt, flushing, amplification, and long-running workload behavior. Adding more callers to the same storage bottleneck can increase backlog instead of improving completed work.',
    term: 'LSM compaction',
    definition: 'Compaction merges eligible sorted files and removes versions that are no longer required under the engine rules. It trades read, write, and space amplification while consuming resources. Snapshot and deletion safety still constrain which records may be removed.',
  },
  {
    chapter: 11,
    prompt: 'Two editors read version 8. The first saves version 9. How should the second avoid silently overwriting that accepted change?',
    options: ['Use an atomic update conditioned on version 8 and handle a conflict', 'Check the version in a separate read, then write unconditionally', 'Assume MVCC rejects every stale business decision', 'Change the local version to 9 and retry without reviewing the change'], correct: 0,
    explanation: 'A version condition must be part of the atomic stored operation. If the expected version is no longer current, the caller can reload and reconcile the intent. A separate check followed by an unconditional write has another race. MVCC controls visible record versions, but does not express every business rule or make all stale overwrites unacceptable automatically.',
    term: 'Optimistic concurrency control',
    definition: 'An operation proceeds using an observed version and checks its assumptions when saving. A failed version condition signals a conflict that the application must handle. This differs from holding a lock while work proceeds and from simply reading an MVCC snapshot.',
  },
  {
    chapter: 9,
    prompt: 'Every database query is tenant-scoped, yet a report download returns another tenant\'s document. What does this reveal?',
    options: ['The tenant filter makes the result impossible', 'Database separation automatically fixes all download permissions', 'Object names alone are authorization', 'Isolation must also cover jobs, caches, result metadata, and downloads'], correct: 3,
    explanation: 'Tenant isolation is an end-to-end property. Correct database filters do not repair a worker with the wrong tenant context, a shared cache key, a wrongly associated object, or a download endpoint that skips authorization. Trace the identity and permission across each boundary and test the actual failing path using synthetic tenants. Separate storage is useful only when routing and access checks remain correct too.',
    term: 'End-to-end tenant isolation',
    definition: 'The authorized tenant scope must remain correct through APIs, stored records, caches, messages, workers, object storage, and exports. Identity comes from verified membership and policy, not an arbitrary caller-supplied tenant parameter or an unpredictable record ID.',
  },
  {
    chapter: 15,
    prompt: 'Two independent edits carry version vectors [1,0] and [0,1]. What relationship do they express?',
    options: ['The second edit certainly happened after the first', 'Concurrent versions under the stated two-participant model', 'Both edits are invalid', 'The first edit must win because its first component is larger'], correct: 1,
    explanation: 'Neither vector is no greater than the other in every component, so they are incomparable under the stated model. That indicates concurrent versions rather than a known causal order. The application still needs a merge, winner, or conflict-resolution policy. Logical metadata identifies relationships; it does not decide whether two edits or reservations can safely be combined.',
    term: 'Vector clock concurrency',
    definition: 'Componentwise comparison can distinguish causal progress from concurrent versions in a defined participant model. Incomparable vectors indicate concurrency. Maintaining identities, counters, membership, and pruning rules has costs, and detecting a conflict is separate from resolving it correctly.',
  },
  {
    chapter: 15,
    prompt: 'A grow-only state-based counter merges [2,0] and [0,3], then receives [0,3] again. What should the displayed total be?',
    options: ['8, because the second delivery is new work', '3, because the most recent message replaces all history', '5, because componentwise maximum makes the repeated state harmless', '2, because remote values are never included'], correct: 2,
    explanation: 'The componentwise maximum is [2,3], and merging [0,3] again leaves that state unchanged. Its total remains 5. This works under the counter\'s ownership, monotonicity, and identity assumptions. Adding received totals would double count shared history. A correct merge for a reaction counter does not imply that exclusive seats, payments, or arbitrary records can use the same rule.',
    term: 'State-based CRDT merge',
    definition: 'A designed merge operation combines replicated state while tolerating repetition and reordering under its assumptions. The grow-only counter uses a maximum per participant and sums the components. Other operations need their own proven structures and invariant analysis.',
  },
  {
    chapter: 15,
    prompt: 'A leader misses several heartbeats. What must be true before a replacement can safely accept protected writes?',
    options: ['A valid ownership protocol prevents conflicting or stale writers', 'One observer has waited any arbitrary timeout', 'A gossip message claims the old process is dead', 'The new machine has a later wall-clock timestamp'], correct: 0,
    explanation: 'A missed heartbeat is evidence of unresponsiveness, not proof that the old process cannot act again. It may be paused or isolated and later resume. Recovery must establish valid ownership using the actual protocol and protect stored effects through terms, quorums, fencing, or another appropriate mechanism. Gossip can spread observations without making them a consensus decision.',
    term: 'Failure suspicion',
    definition: 'A detector suspects failure from observations such as late probes. Network delay and process pauses can produce false suspicion. The policy balances speed against mistakes, while safe writer promotion still requires the coordination and storage rules that enforce ownership.',
  },
  {
    chapter: 17,
    prompt: 'A checkpoint restore emits the same versioned total for one metric window twice. How should an idempotent result sink handle it?',
    options: ['Add both totals unconditionally', 'Treat replay as a second sale', 'Discard all events after a checkpoint', 'Upsert the result under a stable window key and version policy'], correct: 3,
    explanation: 'A result that represents the current total for a window should be replaced or upserted under that window\'s stable identity, not blindly added again. Version rules can prevent an older replay from replacing a newer correction. Delta events require a different deduplication contract. Internal checkpoints do not make an unrelated sink or external side effect exactly once automatically.',
    term: 'Window result publication',
    definition: 'A stream processor must define whether its output is a complete result, correction, or delta. Stable keys, versions, and appropriate sink transactions or idempotency make recovery meaningful. Event-time windows and watermarks do not remove late data or duplicate delivery.',
  },
  {
    chapter: 28,
    prompt: 'All running consumers understand schema version 2. Why might version 1 support still be required?',
    options: ['Because schema compatibility depends only on field count', 'Retained events, DLQs, old clients, backups, and rollback may still produce version 1', 'Because version numbers make every format interchangeable', 'Because every old event must always be deleted immediately'], correct: 1,
    explanation: 'Compatibility must cover the full retention and recovery horizon, not only currently running code. Old events can return through replay, a dead-letter queue, a restored backup, an offline client, or a partner. Test supported fixtures and preserve field meaning, units, and defaults. A registry can check structural rules but cannot infer every business-semantic change.',
    term: 'Replay compatibility',
    definition: 'A newer consumer may need to interpret old retained records correctly long after deployment. The supported horizon includes archives, retries, offline producers, and rollback. Safe evolution plans both record structure and business meaning instead of relying only on schema version labels.',
  },
  {
    chapter: 31,
    prompt: 'An author with millions of followers overwhelms feed fan-out workers. Which approach can reduce that write amplification?',
    options: ['Make every reader wait for every follower entry', 'Remove all current visibility checks', 'Merge that author\'s recent posts at read time within a hybrid feed strategy', 'Assume the average follower count describes every author'], correct: 2,
    explanation: 'A hybrid design can materialize ordinary authors while retrieving selected high-audience authors during a bounded feed read. This reduces enormous per-post write fan-out at the cost of extra read work and merging. The threshold needs workload evidence. Current visibility, privacy, stable pagination, delayed propagation, and duplicate-safe fan-out remain necessary regardless of where candidates are assembled.',
    term: 'Hybrid news-feed fan-out',
    definition: 'Some candidate posts are distributed when written, while others are merged when a reader requests a feed. This balances publication cost and read latency under audience skew. It does not eliminate ranking costs, freshness limits, recovery work, or authorization checks.',
  },
]

export const extendedQuestions: Question[] = items.map((question, index) => ({ ...question, id: `q${index + 33}`, cardId: `q${index + 33}` }))