import type { LessonGuide } from './lesson-guides'

export const supportingLessonNotes: Record<string, readonly [concept: string, example: string, mechanism: string, caveat: string, check: string]> = {
  'Why system designers need a basic hardware model': [
    'Every request uses CPU, memory, storage, and a network. The working set is the data used often; keeping it nearby usually costs less than repeatedly fetching it remotely.',
    'A product page is slow because each request reads the same large catalog from remote storage.',
    'Measure time at each layer, then keep a bounded, reusable part of the catalog in memory.',
    'A cache needs freshness rules and a size limit; it is not the only durable copy.',
    'Compare source reads and tail latency before and after caching the actual working set.',
  ],
  'RAM, disks, and durable writes': [
    'RAM is temporary working memory. Disks retain data, but a successful write may still be buffered. Durable acknowledgement depends on the storage system actually preserving the change.',
    'An upload is reported as complete while its bytes exist only in process memory.',
    'Save the bytes under the required durable-storage policy before confirming completion.',
    'Reading cached data is fine when an authoritative durable copy exists; accepting new data only in RAM is a different promise.',
    'Restart immediately after acknowledgement and verify that the uploaded content is recoverable.',
  ],
  'Processes, threads, and isolation': [
    'A process has its own memory view and resources. Threads execute within a process and share memory, so they can communicate cheaply but can also race over shared state.',
    'Two worker threads update one in-memory order counter and lose an increment.',
    'Use a suitable atomic operation or lock for local shared state, and a database rule for cross-process state.',
    'A lock in one process cannot protect records from another process.',
    'Test simultaneous updates from both threads and separate application instances.',
  ],
  'Garbage collection and language tradeoffs': [
    'Garbage collection reclaims objects that a program can no longer reach. It reduces manual memory errors, but allocation and collection still consume resources and may pause execution.',
    'An image service slows periodically while creating many large temporary objects.',
    'Measure allocation rate, retained memory, and pause time; reduce unnecessary allocations before changing runtimes.',
    'A managed heap limit is not the same as total process memory.',
    'Correlate slow requests with collection pauses and confirm the result on representative image sizes.',
  ],
  'A realistic performance investigation': [
    'Performance work starts by locating the limiting resource. Slow requests can come from CPU work, garbage collection, disk waiting, or a downstream service.',
    'A thumbnail API pauses every few minutes even though its average CPU is low.',
    'Compare request traces with allocation, I/O, and scheduled-job timing, then test one likely cause.',
    'Correlation suggests a cause; changing one relevant factor provides stronger evidence.',
    'Repeat the same workload after the change and compare tail latency, not just the average.',
  ],
  'Data structures shape what a system can do efficiently': [
    'Choose structures by operation: a hash table for exact lookup, an ordered tree for ranges, a trie for prefixes, a heap for priority, and a graph for relationships.',
    'A session map is fast by ID but slow when asked for every session created last hour.',
    'Add an ordered access path for time queries instead of scanning every key.',
    'Big-O describes growth; memory layout, constants, and output size still matter.',
    'Measure exact lookup and range queries separately on realistic data sizes.',
  ],
  'Arrays, lists, stacks, and queues': [
    'Arrays provide direct index access and compact nearby storage. Linked lists connect separate nodes. A stack returns the latest item first; a queue usually returns the oldest first.',
    'A worker uses a growing array and repeatedly shifts every remaining job when removing the first item.',
    'Use a bounded queue structure with efficient front removal and a clear full-queue policy.',
    'Fast queue operations do not make process-memory jobs durable.',
    'Measure enqueue/dequeue cost and verify what happens when capacity is reached.',
  ],
  'Hash tables, sets, and trees': [
    'A hash table maps exact keys to values; a set tracks membership. Ordered trees support sorted traversal and ranges. Hash collisions and resizing add work even when average lookup is fast.',
    'An account screen needs both an exact invoice lookup and a date-sorted invoice history.',
    'Use an exact-key path for one invoice and a suitable ordered index for account history.',
    'One structure rarely optimizes every access pattern.',
    'Test large accounts and bounded date ranges, including many matching results.',
  ],
  'Bloom filters and approximate answers': [
    'Bloom filters compactly answer whether a key may exist. HyperLogLog estimates how many distinct values were seen. Both save memory by providing a narrower answer than an exact record set.',
    'An analytics dashboard needs unique visitors, while checkout must verify an exact order ID.',
    'Use HyperLogLog for a tolerance-based estimate and verify Bloom-filter matches against authoritative records.',
    'A stale Bloom filter can miss newly added keys; estimates are not an exact billing ledger.',
    'Compare with an exact sample and test newly inserted records during filter-update lag.',
  ],
  'Indexes, search, and time-series organization': [
    'An inverted index maps terms to matching documents. Time-series data often groups records by time and another key, making recent ranges and retention easier to manage.',
    'A monitoring dashboard repeatedly scans years of logs to display the last hour.',
    'Use time-bounded partitions and indexes suited to the actual filters, then return a bounded result.',
    'Indexes add write and storage costs, and a large result still takes time to transfer.',
    'Inspect scanned versus returned data for typical and worst-case time ranges.',
  ],
  'A worked example: product autocomplete': [
    'Autocomplete finds useful candidates from a partial query. A small catalog may only need an indexed prefix query; large multilingual catalogs may need a search engine and ranking.',
    'A shopper types a prefix while products are being renamed or removed.',
    'Return a small ranked candidate set, update the derived index by source version, and cache only eligible results.',
    'A suggestion is not proof that a product is currently available or purchasable.',
    'Rename and delete products during indexing lag and verify the final product lookup.',
  ],
  'Threads, tasks, and event loops': [
    'A thread is an execution path. A task represents work or a future result and may share a thread pool. An event loop resumes work when I/O is ready instead of blocking a thread per request.',
    'One CPU-heavy transformation blocks an event loop and delays unrelated requests.',
    'Keep event-loop work short and move CPU-heavy work to bounded workers where appropriate.',
    'Declaring a function async does not make its CPU work parallel.',
    'Measure event-loop delay and request latency while running the expensive transformation.',
  ],
  'Race conditions and atomic operations': [
    'A race occurs when timing changes a result that should be protected. An atomic operation performs a relevant check and change as one indivisible action at the correct owner.',
    'Two buyers both read stock of one and each accepts the last item.',
    'Reserve with a conditional stored update or transaction that permits only one successful decrement.',
    'Separately checking stock and then writing it is not atomic.',
    'Send competing reservations from multiple instances and count accepted results.',
  ],
  'Deadlocks, starvation, and bounded resources': [
    'Deadlock is a cycle of tasks waiting for resources held by one another. Starvation means some work rarely gets a turn. Consistent lock ordering and bounded fair scheduling reduce these risks.',
    'Two transactions acquire account locks in opposite order and wait for each other.',
    'Use a consistent lock order and safely retry a transaction selected as a deadlock victim.',
    'Increasing timeouts alone does not break a waiting cycle.',
    'Run the conflicting access order and verify bounded retries and eventual useful progress.',
  ],
  'Structured cancellation and deadlines': [
    'A deadline bounds how long work is useful. Cancellation asks related work to stop and release resources, but it cannot prove that a remote business effect did not happen.',
    'A caller cancels a payment request after the provider has accepted it.',
    'Stop unnecessary local work, retain the payment ID, and reconcile the provider outcome.',
    'Cancelling the wait is not the same as refunding or preventing a charge.',
    'Cancel before and after provider acceptance and check the saved operation state.',
  ],
  'A worked example: generating invoices': [
    'Bounded concurrency balances useful parallel work against dependency capacity. The worker count should fit database and provider limits rather than the total number of requested invoices.',
    'Launching 1,000 invoice tasks simultaneously overwhelms the database connection pool.',
    'Use a bounded worker pool, persist progress, and retry only unfinished duplicate-safe work.',
    'Async I/O reduces waiting cost but does not create more database capacity.',
    'Compare completion rate, queue age, and connection waiting at several worker limits.',
  ],
  'Layers separate real responsibilities': [
    'Presentation accepts input and displays results. Business logic enforces rules. Persistence reads and writes records. These boundaries make changes easier and keep rules independent of one screen.',
    'A mobile client bypasses the discount checks present only in the web interface.',
    'Apply the discount rule in the server operation used by every client.',
    'A clean folder structure does not help if callers can bypass the authoritative rule.',
    'Submit the same invalid discount through both clients and directly through the API.',
  ],
  'Bounded contexts and data ownership': [
    'A bounded context gives a business term a clear meaning in one area. Billing and marketing may use different customer models without sharing every internal field.',
    'Marketing changes a prospect record that billing mistakenly treats as a verified payer.',
    'Give each context an owner and translate information through explicit contracts.',
    'Sharing a word or identifier does not mean both contexts own the same facts.',
    'Trace a customer change and identify which service may accept each affected business fact.',
  ],
  'Client patterns: MVC, MVP, and MVVM': [
    'MVC separates model, view, and controller. MVP uses a presenter to coordinate a view. MVVM exposes view state and commands through a view model. All organize client presentation responsibilities.',
    'A screen duplicates loading, validation, and retry rules across several controls.',
    'Move shared presentation state into the appropriate controller, presenter, or view model.',
    'These patterns do not decide server deployment or replace backend authorization.',
    'Test loading, failure, and retry states without relying on a manual screen walkthrough.',
  ],
  'A learning-platform example': [
    'A course platform can begin with accounts, content, enrollment, and billing as modules in one application. Put large media in object storage and process videos asynchronously.',
    'A small team wants to create a separate network service for every course table.',
    'Keep clear module ownership first, then extract a service only when independent scaling or releases justify it.',
    'More services add coordination and recovery work without automatically improving the user experience.',
    'Trace an enrollment through payment, access rules, and delayed video processing.',
  ],
  'Images, runtimes, and resource limits': [
    'An image packages files and startup configuration; a runtime creates the running container. CPU and memory limits constrain it, while writable layers may disappear when it is replaced.',
    'A container is killed under load despite having enough free host memory.',
    'Check its configured memory limit, total process use, and restart reason.',
    'The container limit can be lower than host capacity, and heap use is only part of process memory.',
    'Repeat the workload with measured limits and verify recovery without lost accepted work.',
  ],
  'Cloud service models': [
    'IaaS provides infrastructure, PaaS manages more of the application platform, and SaaS delivers a finished product. Serverless manages execution, but you still own application data, contracts, and access rules.',
    'A burst of managed functions opens more connections than the database can accept.',
    'Choose the model by required control and operating effort, then bound downstream concurrency.',
    'Managed scaling does not make every dependency unlimited.',
    'Test a realistic burst and inspect database waiting, throttling, and accepted-job recovery.',
  ],
  'Cloud-native principles': [
    'Cloud-native design treats instances as replaceable and relies on automated deployment, explicit configuration, observability, and recoverable state. It is a set of operating practices, not a product checklist.',
    'An application loses active jobs whenever an instance is replaced during a deployment.',
    'Persist accepted jobs and make startup, shutdown, and retries safe for replacement.',
    'Running in a container does not by itself make an application resilient.',
    'Replace instances during a test workload and verify completed and pending operations.',
  ],
  'Kubernetes architecture': [
    'Kubernetes reconciles desired state with observed state. Controllers maintain resources, the scheduler places workloads on nodes, and runtimes execute containers.',
    'A deployment requests three replicas, but one pod stays pending.',
    'Inspect placement events, available resources, and workload constraints before increasing replicas.',
    'Desired replica count is not usable capacity, and readiness is different from process existence.',
    'Remove a test instance and verify rescheduling, startup, and traffic readiness.',
  ],
  'Scaling and stateful workloads': [
    'Scaling changes serving capacity only when resources and dependencies are available. Stateful workloads also need valid data ownership, replication, recovery, and storage lifecycle rules.',
    'An autoscaled database pod starts successfully but is not a valid writable replica.',
    'Use the database replication protocol and readiness checks before routing protected writes.',
    'A StatefulSet supplies stable workload identity, not automatic database consensus or backups.',
    'Replace a member and verify stored data, exclusive write ownership, and application recovery.',
  ],
  'A practical decision': [
    'Choose a platform from workload, team skills, control requirements, and operating cost. A managed app platform can suit a small API; a shared container platform can suit many independently operated services.',
    'A small team spends more time managing a cluster than improving its internal app.',
    'Compare a simpler managed deployment against the actual security, reliability, and scale requirements.',
    'A popular platform is not automatically the lowest-risk choice for every team.',
    'Estimate the full release, monitoring, recovery, and maintenance effort for both choices.',
  ],
  'Architecture includes how change reaches production': [
    'A design must work during change as well as after deployment. Old binaries, retained messages, and database migrations can overlap, so release compatibility is part of architecture.',
    'A new release removes a field still read by an older application instance.',
    'Use compatible additions, migrate readers and data, then retire the old contract.',
    'A healthy new instance does not prove the mixed-version system is safe.',
    'Run old and new versions together and exercise the rollback or forward-repair plan.',
  ],
  'Tests protect different boundaries': [
    'Unit tests check local rules, integration tests check real boundaries, and end-to-end tests check user journeys. Load, stress, security, and long-running tests answer different risk questions.',
    'Mocks pass while the real database accepts conflicting reservations.',
    'Test local decisions quickly, then verify storage invariants and failure paths with real isolated dependencies.',
    'A large test count is not evidence that the risky boundary was exercised.',
    'Map each important guarantee to the cheapest test that can actually disprove it.',
  ],
  'Test failure windows, not only the happy path': [
    'A failure window is the gap between two steps that do not commit together. Crashing inside that gap exposes whether retry and recovery preserve the intended result.',
    'A queue worker commits an invoice and crashes before acknowledging its message.',
    'Replay the message with the same operation identity and verify that it does not create another invoice.',
    'Mocks cannot prove real retention, lock expiry, or transaction behavior.',
    'In an isolated environment, interrupt work immediately before and after each important commit.',
  ],
  'Mobile releases are slower to converge': [
    'Users may keep old mobile app versions long after a server release. Store review, staged rollout, and delayed updates make backward-compatible APIs important.',
    'A backend removes a response field that an installed older app still requires.',
    'Preserve supported contracts, monitor client versions, and deprecate behavior through a planned migration.',
    'Remote configuration cannot repair every incompatible protocol or security issue.',
    'Run fixtures from supported old clients against the new backend before release.',
  ],
  'Git as a history model': [
    'Git stores commits connected by parent relationships. A branch points to a commit. Merge combines histories; rebase reapplies changes and creates new commit identities.',
    'A developer rebases a shared branch and colleagues can no longer match their previous commits.',
    'Follow the team\'s shared-history policy and connect releases to identifiable commits and artifacts.',
    'A clean merge or linear history does not prove runtime correctness.',
    'Trace a deployed artifact back to its source, configuration, and migration state.',
  ],
  'Monorepos, multiple repositories, and collaboration': [
    'A monorepo keeps several projects together; multiple repositories separate their histories and access. Choose by ownership, coordinated changes, tooling, and permissions, not by a universal rule.',
    'A shared API change requires synchronized edits across several repositories.',
    'Define contract owners and versioned migration steps, or use coordinated changes where shared tooling supports them.',
    'One repository does not imply one deployable application.',
    'Walk through a cross-project change and compare review, testing, and release effort.',
  ],
  'Diagrams and technical communication': [
    'Use context diagrams for boundaries, sequence diagrams for interactions, state diagrams for lifecycles, and data diagrams for relationships. Each arrow should describe a meaningful operation.',
    'A payment diagram shows a successful call but hides what happens when its reply is lost.',
    'Add the durable state and uncertainty window, then trace the retry using the same payment identity.',
    'A diagram tool does not supply architecture or prove recovery.',
    'Ask another engineer to explain one success and one failure path using only the drawing.',
  ],
  'Why operating-system knowledge belongs in system design': [
    'Applications use processes, memory, files, sockets, permissions, and scheduled CPU time. Operating-system limits can break an otherwise reasonable API design.',
    'A healthy-looking server stops accepting requests because it has no free file descriptors.',
    'Check process limits, open sockets, and resource use alongside request traces.',
    'Low CPU does not rule out exhausted connections, storage, or other limits.',
    'Identify the exhausted resource before increasing application replicas.',
  ],
  'The boot path': [
    'A Linux host typically starts through firmware, bootloader, kernel, and a service manager. A container normally starts a process using the existing host kernel.',
    'The host is ready, but an application still fails while loading its configuration.',
    'Separate host boot, container startup, application initialization, and traffic readiness when investigating.',
    'A booted machine is not proof that the application is ready for user requests.',
    'Inspect startup events at the failing layer and verify the real readiness condition.',
  ],
  'Files, directories, and mounts': [
    'A filesystem places local or remote storage under paths. Open handles can retain a deleted file\'s data, and limits include free bytes, metadata, permissions, and mount availability.',
    'A deleted log file still occupies space because the application keeps it open.',
    'Identify the open handle and use the approved log-rotation or reopen procedure.',
    'A container path may use temporary storage that disappears during replacement.',
    'Check open files, mount type, and storage lifecycle before assuming a path is durable.',
  ],
  'Permissions and process identity': [
    'File access depends on the effective user, groups, path permissions, and additional policies. Directory execute permission allows traversal. Give services only the access their operations need.',
    'A service can read a filename but cannot traverse one of its parent directories.',
    'Inspect the complete path and effective identity, then correct the specific missing permission.',
    'Broad administrator access may hide the error while exposing unrelated data.',
    'Verify the required operation succeeds and an unrelated protected path remains inaccessible.',
  ],
  'SSH and remote access': [
    'SSH protects a remote connection and authenticates its endpoints. Host-key verification helps confirm the server; private client keys must stay private.',
    'A changed host key appears during an otherwise routine connection.',
    'Verify the change through the approved independent channel before trusting the endpoint.',
    'Encryption to an unverified server does not prove it is the intended machine.',
    'Use scoped, auditable access and confirm how credentials are rotated and revoked.',
  ],
  'Observe CPU, memory, I/O, and scheduling': [
    'Observe the resource that requests wait for. CPU averages can hide one busy thread; total memory exceeds the managed heap; I/O queues and connection limits can cause slowness with low CPU.',
    'An API slows down while its CPU graph stays almost flat.',
    'Correlate request traces with database-pool waiting, storage latency, memory pressure, and scheduling.',
    'Linux load average is not just CPU utilization; it includes certain waiting tasks.',
    'Compare the same time window across request and resource measurements.',
  ],
  'Diagnostic tools and what they answer': [
    'top summarizes processes; vmstat helps with memory and scheduling; iostat examines storage; ss shows sockets; lsof relates files to processes. A profiler locates where execution time is spent.',
    'A CPU profiler shows little work because requests are waiting for database connections.',
    'Start with connection and wait measurements, then profile CPU only if computation is the suspected limit.',
    'Diagnostic output can contain sensitive data and the tools themselves have overhead.',
    'Choose one low-cost observation that distinguishes your leading explanation from an alternative.',
  ],
  'A disciplined debugging loop': [
    'Describe the failure, state one testable explanation, and choose a check that could disprove it. Change one relevant factor, compare outcomes, and keep a regression test.',
    'Latency rises immediately after more API replicas are added.',
    'Check the combined connection pools and database waiting before changing load-balancer algorithms.',
    'The last visible change is a useful clue, not proof of cause.',
    'Reproduce the workload with a bounded connection budget and compare completion rate and latency.',
  ],
  'Runtime choices in context': [
    'Runtimes differ in startup, compilation, memory management, concurrency, and tooling. A good choice for CPU-heavy processing may not be the simplest choice for a network-heavy API.',
    'A rewrite improves a small benchmark but does not fix production database waiting.',
    'Measure the real workload and bottleneck, including warmup and operating effort, before selecting a runtime.',
    'No language wins every workload or removes distributed-system failure handling.',
    'Compare complete user operations, resource use, and recovery with equivalent implementations.',
  ],
}

export const supportingLessonGuides: Record<string, LessonGuide> = {
  'Images, runtimes, and resource limits': {
    reasoning: 'A CPU limit and a memory limit fail differently. CPU throttling can increase latency while the process stays alive, whereas exceeding a hard memory limit may terminate it. Inspect the actual termination or throttling evidence before treating every slow or restarted container as an application-code exception.',
    explanation: 'An image contains packaged filesystem layers and startup configuration. A container runtime creates the running process environment from that image. Resource controls constrain CPU, memory, and other use, while mounts determine which data has a lifetime beyond the container.',
    keyPoints: ['An image is not a snapshot of every later writable change.', 'A memory limit can be reached while the host still has free memory.', 'Readiness and restart policies should reflect actual application behavior.'],
    steps: ['Package a reproducible application with explicit startup configuration.', 'Set resource limits and persistent mounts from measured requirements.', 'Inspect exit reasons and test replacement, startup, and accepted-work recovery.'],
    example: 'A service uses a 512 MB managed heap but also allocates native buffers and thread stacks. Its total memory exceeds a 600 MB container limit and it is killed. Looking only at the heap chart hides the cause. Measure total process use and bound allocations rather than assuming free host RAM prevents termination.',
    decision: 'Keep secrets outside public images and avoid storing authoritative data only in temporary writable layers. Version and test configuration with the workload.',
    remember: 'Image contents, running resources, and persistent state have different lifecycles.',
  },
  'Cloud service models': {
    reasoning: 'Compare responsibilities task by task rather than assuming one service model is always easier. A platform may manage operating-system patches while you still choose database permissions, recovery retention, and application limits. The useful question is which work disappears, which remains, and which constraints the service introduces.',
    explanation: 'Infrastructure as a Service supplies infrastructure primitives such as virtual machines. Platform as a Service manages more of application hosting. Software as a Service delivers a finished application. Serverless execution manages provisioning around functions or services. Each shifts responsibility rather than eliminating it.',
    keyPoints: ['More management can reduce operating work but also limit control.', 'Your data model and authorization remain your responsibility where you build the application.', 'Provider limits, region choice, pricing, and recovery features vary.'],
    steps: ['List required control, compliance, scale, and team operating capabilities.', 'Choose the simplest service model that meets those requirements.', 'Verify remaining responsibilities such as backups, identity, limits, and application recovery.'],
    example: 'A small team hosts an internal API on a managed application platform instead of operating a cluster. The provider handles host replacement, but the team still configures database retention and resource permissions. A burst can also exceed the database limit even when the hosting platform scales compute automatically.',
    decision: 'Compare total operating cost and risk, not just machine price. Use lower-level infrastructure when the workload genuinely needs its control.',
    remember: 'Managed service means shared responsibility, not no responsibility.',
  },
  'Cloud-native principles': {
    reasoning: 'Replaceability includes shutdown behavior. An instance should stop accepting new work, finish or safely release owned work, and leave durable progress for another instance. Handling only startup makes deployments fragile because a healthy platform may terminate an old process while its accepted jobs are still running.',
    explanation: 'Cloud-native practices make applications operable when infrastructure changes routinely. They emphasize replaceable instances, automated releases, explicit configuration, observability, and recoverable state. A container or cloud account alone does not create those properties.',
    keyPoints: ['Assume instances can restart or move.', 'Keep configuration and credentials controlled rather than embedded in ad hoc hosts.', 'Measure real service outcomes and design recovery before failure occurs.'],
    steps: ['Separate durable accepted state from temporary execution state.', 'Automate repeatable build, deployment, health, and shutdown behavior.', 'Exercise replacement and dependency failure while verifying the business contract.'],
    example: 'A containerized service still stores accepted email jobs only in an in-memory queue. A rolling deployment loses them. Persisted job intent and duplicate-safe workers make replacement safe; container packaging by itself did not change the reliability of that queue.',
    decision: 'Adopt practices that solve real delivery and recovery needs. Avoid accumulating platform components simply to match a cloud-native checklist.',
    remember: 'Design for routine change and replacement, not just for running on a cloud host.',
  },
  'Kubernetes architecture': {
    reasoning: 'A controller repeatedly compares desired and observed state; it does not guarantee every correction succeeds immediately. A pod can remain pending because no eligible node has capacity, or fail readiness because its dependency is unavailable. Inspect the reason at the failing stage rather than repeatedly increasing the requested replica count.',
    explanation: 'Kubernetes accepts desired state through its API and uses controllers to reconcile observed differences. A scheduler chooses nodes for pods; node agents and runtimes manage execution. Networking, storage, and application readiness complete the path from desired replicas to useful service.',
    keyPoints: ['Pending pods are desired work, not serving capacity.', 'A running process can still fail readiness.', 'Controllers reconcile platform resources, not arbitrary business transactions.'],
    steps: ['Declare workloads, resource needs, configuration, services, and storage requirements.', 'Inspect scheduling and startup events when observed state differs from the declaration.', 'Use readiness and graceful termination so only eligible instances receive traffic.'],
    example: 'A deployment requests ten replicas but only six fit on available nodes. Increasing the desired count again does not create capacity. Resource requests, placement constraints, and cluster provisioning determine whether the remaining pods can run. Their database connection budgets must also fit downstream capacity.',
    decision: 'Use orchestration when its operating benefits justify the complexity. Test workload-specific recovery rather than assuming reconciliation guarantees data correctness.',
    remember: 'Desired state becomes useful capacity only after placement, startup, and readiness.',
  },
  'Scaling and stateful workloads': {
    reasoning: 'Storage attachment is not proof of current write authority. A restarted instance may hold valid bytes yet still be an old owner or lagging replica. Let the database\'s recovery and membership protocol determine eligibility, and use platform readiness to reflect that decision instead of replacing it.',
    explanation: 'Stateless compute can often be replaced freely, but stateful owners need identity, durable storage, replication, and a safe authority-transfer protocol. Orchestration can restart a process without knowing whether that process is eligible to accept writes.',
    keyPoints: ['Stable pod identity is not database consensus.', 'Storage lifecycle and attachment behavior affect replacement.', 'Scaling must respect data partitioning and downstream limits.'],
    steps: ['Define who owns each state partition and how ownership is recovered.', 'Configure storage, replication, and readiness with the database or application\'s supported protocol.', 'Test restarts, partitions, and delayed old writers during takeover.'],
    example: 'A database pod restarts with its volume attached, but it has not caught up to the required replication position. Routing writes immediately can violate the cluster protocol. Database-aware readiness and promotion rules must establish eligibility before ordinary traffic reaches it.',
    decision: 'Use operators and managed services only after checking what guarantees they actually automate. Backups and restore drills remain necessary.',
    remember: 'Starting a stateful process is not the same as making it the valid state owner.',
  },
  'A practical decision': {
    reasoning: 'Include the cost of uncommon but important operations: restoring a backup, rotating credentials, diagnosing a failed release, and replacing a region. A platform that is inexpensive during a demo may require skills the team cannot reliably supply during those events. A simpler supported service can reduce that operating risk.',
    explanation: 'Platform choice is a tradeoff among control, operating effort, workload needs, and cost. The most flexible platform is not always the safest choice for a small team. A simpler managed deployment can make releases and recovery more predictable when specialized control is unnecessary.',
    keyPoints: ['Include maintenance, monitoring, and incident response in total cost.', 'Check provider limits and required features before committing.', 'Prefer measured needs over anticipated complexity that may never arrive.'],
    steps: ['Write the workload, reliability, security, and deployment requirements.', 'Compare a small set of suitable platforms against those requirements.', 'Run a realistic deployment and recovery exercise before choosing the added complexity.'],
    example: 'An internal API has modest traffic and a small team, yet a custom cluster consumes most engineering time. A managed app service and database may meet the same quality targets with less operational work. A specialized low-latency workload might justify more control, but that is a different requirement.',
    decision: 'Choose a path that can evolve without prematurely building a platform team. Record why the current choice is sufficient and what would trigger reevaluation.',
    remember: 'The right platform fits both the workload and the people operating it.',
  },
  'Architecture includes how change reaches production': {
    reasoning: 'Release order matters when a new writer produces data an old reader cannot understand. Make readers tolerant before enabling the new format, then retire the old path after compatibility evidence permits it. This staged transition avoids requiring every process and client to update at exactly the same moment.',
    explanation: 'A system must remain understandable during rollout, not only after every instance is upgraded. Binaries, schemas, configuration, queues, and external clients change on different schedules. Compatibility and recovery therefore belong in architecture discussions from the start.',
    keyPoints: ['Old and new versions often run together.', 'Data migrations can outlive an application rollout.', 'Rollback of code may leave already changed data or external effects intact.'],
    steps: ['Identify all components and stored formats affected by the change.', 'Create a compatible transition with controlled rollout and measurable acceptance gates.', 'Plan rollback or forward repair for every irreversible step.'],
    example: 'A new API writes an enum value that old workers cannot understand. Even if the API rollout succeeds, queued work fails on the old workers. Deploying compatible readers before new writers, with mixed-version tests, protects the transition rather than relying on simultaneous release timing.',
    decision: 'Prefer incremental compatible changes. Treat deployment strategy as part of the behavior and failure model, not just the final pipeline command.',
    remember: 'A design must work while it changes, not only once the change is complete.',
  },
  'Tests protect different boundaries': {
    reasoning: 'A test double models only the behavior someone programmed into it. It can verify the application response to a conflict, but not whether the real database detects that conflict. Pair the local test with a focused real-boundary check so both the reaction and its triggering guarantee have evidence.',
    explanation: 'Test types answer different questions. Unit tests exercise local rules, integration tests verify real boundaries, contract tests check consumer agreement, and end-to-end tests follow user journeys. Load, stress, security, and long-running tests target other risks and can overlap these categories.',
    keyPoints: ['A mock cannot prove the real dependency\'s transaction or retention behavior.', 'A high test count can still miss the critical failure window.', 'Choose the cheapest check that can actually disprove the claimed guarantee.'],
    steps: ['List the important promises and where each is enforced.', 'Map each promise to a focused test at that boundary.', 'Combine fast checks with selected realistic integration and workflow tests.'],
    example: 'A unit test verifies that the application reacts correctly to a duplicate-key error. An integration test sends concurrent inserts to confirm the database constraint exists. An end-to-end test checks that the losing customer sees an honest reservation result. Each test protects a different part of the same promise.',
    decision: 'Use risk to choose coverage instead of requiring every scenario to run through the whole UI. Keep failures diagnosable and test data isolated.',
    remember: 'Test where the guarantee lives, and know what the test does not prove.',
  },
  'Test failure windows, not only the happy path': {
    reasoning: 'Assert what the user was promised before the interruption. A recovered system with no duplicate rows can still be wrong if it silently lost an acknowledged operation. Record expected accepted identities before injecting the failure, then verify that recovery preserves those outcomes as well as rejecting unwanted repeats.',
    explanation: 'A failure window lies between steps that do not commit together. Crashing before and after the boundary reveals whether recovery loses work, repeats effects, or reports a false outcome. These tests are especially important for queues, caches, payments, and multi-step workflows.',
    keyPoints: ['An acknowledged transport operation is not always a completed business operation.', 'Retries must preserve operation identity.', 'Use approved isolated environments and explicit stop conditions for fault experiments.'],
    steps: ['Mark each independent commit, publication, and acknowledgement in the flow.', 'Interrupt execution at the gaps using a controlled test mechanism.', 'Resume and assert accepted data, external effects, and user-visible status.'],
    example: 'A worker creates an invoice and crashes before acknowledging the job. Redelivery should find the existing invoice by its stable key. Crashing before the invoice transaction commits should instead allow safe creation on retry. Testing both sides distinguishes duplicate safety from accidental message loss.',
    decision: 'Use real integrations where mocks cannot reproduce settlement or transaction semantics. Avoid unapproved production fault injection.',
    remember: 'The interesting test is often the pause between two successful steps.',
  },
  'Mobile releases are slower to converge': {
    reasoning: 'Keep fixtures from real supported client versions rather than testing only the latest SDK. Old clients may handle unknown enum values or missing fields differently. Server telemetry can show adoption, but it cannot replace a deliberate support policy for users who update slowly or reconnect after a long absence.',
    explanation: 'Mobile binaries reach users through packaging, signing, distribution, and sometimes store review. Users can delay updates, so the backend often supports several generations simultaneously. A server deployment cannot assume it has replaced every consumer.',
    keyPoints: ['Additive contracts help only when old clients tolerate the addition.', 'Capabilities and deprecation policies need clear lifetimes.', 'Remote configuration cannot repair every incompatible binary or protocol.'],
    steps: ['Identify supported client versions and the contracts they use.', 'Introduce compatible server changes and monitor adoption.', 'Retire old behavior only after the policy and observed usage permit it.'],
    example: 'A backend removes a field after the latest mobile version stops using it. A customer who has not updated still needs that field and sees a broken screen. Historical client fixtures in contract tests expose the problem before release, while capability negotiation can support gradual transitions.',
    decision: 'Design a realistic support window instead of promising indefinite compatibility. Security-critical retirements may need a deliberate minimum-version policy.',
    remember: 'Deploying the server does not deploy every client.',
  },
  'Git as a history model': {
    reasoning: 'A commit identifies source content, while a branch name moves as commits are added. Record the exact commit and built artifact for a release instead of only the branch name. Rebase creates new commit identities, so rewriting a shared branch can invalidate references other contributors still use.',
    explanation: 'Git stores content-addressed objects and commits linked by parents. A branch is a movable reference to a commit. Merge preserves and joins histories; rebase recreates commits on another base. Understanding this graph makes collaboration and release investigation more predictable.',
    keyPoints: ['Rebased commits have new identities even when their changes look similar.', 'Rewriting shared history can disrupt other contributors.', 'Source history is only one part of deployed system state.'],
    steps: ['Use branches and review according to the team\'s collaboration policy.', 'Merge or rebase with awareness of which history is already shared.', 'Connect releases to source commits, built artifacts, configuration, and migration records.'],
    example: 'An incident begins after a release. Git identifies the code change, but production also received a new feature flag and database migration. Reverting the commit may not restore the earlier behavior unless those changes are considered too. A traceable artifact and deployment record complete the investigation.',
    decision: 'Do not use history rewriting to hide or casually replace collaborators\' work. A visually linear graph is not automatically safer than a documented merge history.',
    remember: 'Git explains source changes; deployment evidence explains what actually ran.',
  },
  'Monorepos, multiple repositories, and collaboration': {
    reasoning: 'Coordinated source changes are not necessarily coordinated deployment. A monorepo can update an API and its clients in one review, but old deployed clients may remain active. Keep compatible release ordering even when all related code lives together, and use ownership rules to prevent unrelated teams from changing private contracts casually.',
    explanation: 'A monorepo keeps multiple projects in one repository, enabling coordinated changes and shared tooling. Multiple repositories separate histories and can reinforce ownership or access boundaries. Neither layout determines whether the system has one or many deployable services.',
    keyPoints: ['Cross-project coupling exists regardless of repository layout.', 'Large monorepos need selective builds and clear ownership.', 'Multiple repositories need coordinated dependency and contract evolution.'],
    steps: ['Examine how teams change and release related components.', 'Choose repository boundaries and tooling that support those workflows and permissions.', 'Test a representative cross-project change from review through deployment.'],
    example: 'An API and three consumers require a compatible change. A monorepo can review related source together but still needs safe rollout order. Separate repositories can release independently only when the contract allows mixed versions. Repository choice does not remove the compatibility problem.',
    decision: 'Choose from team scale, tooling, permissions, and change patterns. Avoid using repository count as a proxy for architectural independence.',
    remember: 'Organize collaboration around real ownership and change, not a universal repository rule.',
  },
  'Diagrams and technical communication': {
    reasoning: 'Label whether an arrow means a request, a committed fact, or a best-effort notification. These can look identical in a drawing but imply different retry and recovery rules. Showing the acknowledgement and saved-state boundary helps readers understand what remains true if the next arrow never occurs.',
    explanation: 'A useful diagram answers a specific question. Context views show boundaries, deployment views show running responsibilities, sequences show interactions, and state machines show valid transitions. Combining every detail into one picture can hide the important behavior.',
    keyPoints: ['Give each arrow a meaning and each store an owner.', 'Mark accepted state and uncertainty windows explicitly.', 'Distinguish hypothetical examples from verified current implementations.'],
    steps: ['Choose the question and audience for the diagram.', 'Draw only the components and relationships needed to explain it.', 'Walk a success and a failure through the drawing and revise ambiguous labels.'],
    example: 'A payment sequence shows request and success arrows but no saved operation ID. Asking what happens when the success reply is lost exposes the missing recovery path. Adding the provider identity, durable status, and reconciliation step teaches more than adding several unrelated infrastructure boxes.',
    decision: 'Use multiple complementary views when structure and lifecycle both matter. The tool that draws the picture does not determine the architecture.',
    remember: 'A good diagram makes an important claim easier to verify.',
  },
  'Why operating-system knowledge belongs in system design': {
    reasoning: 'Resources often have limits below the whole-machine total. A process can exhaust file descriptors, a container can reach its memory cap, or a connection pool can fill while the host looks healthy. Inspect the boundary enforcing the limit, because adding unrelated host capacity may not change it.',
    explanation: 'Applications depend on operating-system resources even when hosted through managed layers. Processes need scheduled CPU time, memory, file descriptors, sockets, and permitted storage paths. Exhausting one of these resources can make an API fail while its high-level architecture still looks reasonable.',
    keyPoints: ['A service can be slow because it waits, not because it computes too much.', 'Limits may apply per process, container, user, or host.', 'Investigations should avoid exposing credentials or private payloads.'],
    steps: ['Connect the failing request to the process and resources it uses.', 'Inspect the relevant limits and waiting behavior over the incident window.', 'Correct the demonstrated resource problem and verify the user operation.'],
    example: 'A server stops opening new outbound connections after leaking sockets. CPU and free memory appear healthy, but file-descriptor use reaches its limit. Raising the limit may buy time; fixing connection lifecycle and bounding concurrency addresses the cause.',
    decision: 'Learn what each tool measures and use the approved access path. Avoid broad administrative changes based on a single symptom.',
    remember: 'Operating-system limits are part of the application\'s real capacity.',
  },
  'The boot path': {
    reasoning: 'Startup dependencies need explicit readiness, not just an assumed order. A service manager may launch the database process before the API, but the database can still be recovering. The API should use bounded startup or retry behavior and report readiness only when its required initialization actually completes.',
    explanation: 'A typical Linux host starts through firmware, a bootloader, kernel initialization, and a first user-space process such as systemd. Services then start under configured dependencies. Containers usually start processes on an already running host kernel rather than booting a separate kernel.',
    keyPoints: ['Host boot, container startup, and application readiness are distinct stages.', 'A process may start before its configuration or dependencies are usable.', 'The visible failure location helps choose which logs and events to inspect.'],
    steps: ['Identify the last startup stage known to have succeeded.', 'Inspect events and configuration at the next failing stage.', 'Verify actual application readiness before routing user traffic.'],
    example: 'A virtual machine is reachable by SSH, but its API cannot load a required secret and repeatedly exits. Rebooting the host does not repair the missing application permission. Inspecting service startup logs and the configured identity locates the problem at the correct layer.',
    decision: 'Avoid equating machine reachability with a ready business service. Use separate probes and recovery actions for the relevant stage.',
    remember: 'A booted operating system is only the start of application readiness.',
  },
  'Files, directories, and mounts': {
    reasoning: 'A path can resolve to a different storage layer after deployment if a mount is missing or changed. The application may then write successfully into an ephemeral local directory instead of the intended persistent volume. Verify the backing mount and lifecycle, not only whether the filename exists.',
    explanation: 'A filesystem presents paths over storage that may be local, remote, persistent, read-only, or temporary. Metadata and open handles influence behavior as much as filenames. Removing a directory entry does not necessarily release storage while a process retains the open file.',
    keyPoints: ['Free bytes, inode availability, and permissions are separate constraints.', 'Mounts determine which storage a path actually uses.', 'Container writable layers may disappear during replacement.'],
    steps: ['Identify the path, backing mount, access mode, and lifecycle.', 'Inspect open handles and both data and metadata capacity.', 'Use the approved cleanup or rotation procedure and verify recovery of required data.'],
    example: 'An administrator deletes a huge log but disk use does not fall. The application still has the file open and continues writing through its handle. A supported log-reopen or rotation procedure releases that handle. Deleting more unrelated files would miss the mechanism and risk data loss.',
    decision: 'Do not assume a familiar path is persistent across redeployment. Give accepted uploads and job records an explicit durable storage home.',
    remember: 'A path is a name; the mount and open handles determine much of its behavior.',
  },
  'Permissions and process identity': {
    reasoning: 'A command working in your interactive session does not prove it works for the service account. Different groups, environment, working directory, and access policies can change the result. Reproduce the relevant operation under the approved service context and fix the narrow difference rather than granting broad administrator privileges.',
    explanation: 'Access depends on the effective identity, groups, path traversal, file permissions, and potentially ACLs, capabilities, or mandatory policies. A directory\'s execute permission permits traversal. The right investigation follows the exact denied operation rather than granting broad access immediately.',
    keyPoints: ['The service identity may differ from the interactive user.', 'Every parent directory can affect path access.', 'Least privilege reduces the impact of mistakes and compromised processes.'],
    steps: ['Identify the effective process identity and requested operation.', 'Check the complete path and all relevant access policies.', 'Grant only the required access, then verify both allowed and forbidden operations.'],
    example: 'A service account can read a report file\'s mode bits but cannot traverse a parent directory. Running the service as administrator hides the problem and expands risk. Correcting the specific directory permission preserves access to the report without granting unrelated data access.',
    decision: 'Use approved ownership and credential-management procedures. Never print secret files or full environments merely to investigate a permission error.',
    remember: 'Fix the specific access contract, not every permission on the machine.',
  },
  'SSH and remote access': {
    reasoning: 'Host authentication and user authentication protect different directions of trust. The client checks that it reached the intended server, while the server checks who is connecting. Supplying a valid private client key does not remove the need to verify a changed host key through a trusted channel.',
    explanation: 'SSH protects a remote channel and authenticates its endpoints. The client verifies the server through host-key trust, while the server verifies an allowed client identity. Encryption alone does not establish that the endpoint is the intended host.',
    keyPoints: ['Private keys should not be shared through logs, chat, or source control.', 'Unexpected host-key changes require independent verification.', 'Access should be scoped, auditable, and revocable.'],
    steps: ['Use the organization\'s approved access path and credential mechanism.', 'Verify the host identity and connect with the minimum required privileges.', 'Perform bounded diagnostics and retain an audit trail without exporting sensitive data unnecessarily.'],
    example: 'A familiar hostname suddenly presents a different SSH host key. It could be a legitimate replacement or a wrong endpoint. Blindly deleting the trusted key and accepting the new one removes the warning without resolving its cause. Confirm the expected change through a trusted independent channel first.',
    decision: 'Prefer managed or short-lived access where appropriate. Do not open broad inbound access or bypass host verification just to make troubleshooting convenient.',
    remember: 'A protected connection must reach a verified and authorized endpoint.',
  },
  'Observe CPU, memory, I/O, and scheduling': {
    reasoning: 'Measure per-core and per-process behavior when machine averages seem inconsistent with latency. One busy thread can limit a request stage while most cores remain idle. Similarly, time waiting for I/O can produce little CPU activity. Both cases require different changes from simply adding more parallel requests.',
    explanation: 'Resource measurements explain different kinds of waiting and work. CPU utilization can hide one saturated thread. Linux load average includes runnable work and certain uninterruptible waits. Memory includes heap, native allocations, mappings, and caches; I/O introduces queues and latency.',
    keyPoints: ['Low CPU does not prove spare capacity at every dependency.', 'Compare request and resource metrics over the same period.', 'Check limits as well as utilization, including connections and descriptors.'],
    steps: ['Locate the slow operation and distinguish computation from waiting.', 'Inspect the resource most likely to explain that delay.', 'Correlate independent evidence and test a targeted change under comparable load.'],
    example: 'After adding API replicas, requests wait longer while each host\'s CPU stays low. The combined database pools create more contention than the database can serve. Pool wait time and database saturation explain the symptom better than increasing CPU or assuming network routing is at fault.',
    decision: 'Use several aligned measurements rather than one dashboard tile. A larger machine may temporarily hide unbounded queues or leaks without fixing them.',
    remember: 'Find the scarce resource or wait, not just the busiest-looking chart.',
  },
  'Diagnostic tools and what they answer': {
    reasoning: 'A sampled CPU profile answers where execution occurred during its sampling period. It does not automatically show time waiting for network or pool availability. Start with an end-to-end timing breakdown, then choose CPU profiling, I/O measurements, or lock inspection based on which part actually accounts for the delay.',
    explanation: 'Tools are useful when their output discriminates between explanations. top summarizes processes, vmstat covers system activity, iostat focuses on storage, ss inspects sockets, and lsof relates open files to processes. Profilers and tracing tools answer more focused execution questions.',
    keyPoints: ['A CPU profile shows sampled execution, not every source of wall-clock waiting.', 'Flame-graph width represents sample share, not a left-to-right timeline.', 'Tool overhead and sensitive output require deliberate scope.'],
    steps: ['State the suspected cause and what evidence would contradict it.', 'Choose the lowest-cost permitted tool that measures that behavior.', 'Compare the observation with request traces and verify any proposed correction.'],
    example: 'A CPU profile is nearly empty during slow requests because threads are waiting for a database connection. Inspecting pool metrics and socket state is more useful. If instead a transformation loop dominates samples, an execution profile can point directly to the expensive computation.',
    decision: 'Avoid collecting every possible dump by default. Use bounded diagnostics and redact or avoid private information that is not needed.',
    remember: 'Choose a tool for the question it can answer.',
  },
  'A disciplined debugging loop': {
    reasoning: 'State the expected discriminating result before running a check. If database-pool waiting causes the slowdown, limiting aggregate connections should change that waiting and improve completion under the same load. If neither changes, revise the explanation instead of accepting the edit merely because it looks plausible.',
    explanation: 'Debugging is controlled hypothesis testing. A precise symptom and a falsifiable explanation reduce random changes. Compare healthy and failing cases, find the nearest behavior that controls the result, and choose a small check before widening the investigation.',
    keyPoints: ['One observation rarely proves causality by itself.', 'A focused change makes before-and-after results easier to interpret.', 'Regression evidence prevents the same failure from returning.'],
    steps: ['Describe the input, expected result, actual result, and failure conditions.', 'Form one local explanation and run a check that could disprove it.', 'Repair the controlling behavior, rerun the same check, and add appropriate regression coverage.'],
    example: 'A price display becomes stale after an update. Rather than clearing every cache repeatedly, pause a read before invalidation and let it refill afterward. Reproducing that order demonstrates the stale-fill race. A version-aware fill can then be verified against the same controlled sequence.',
    decision: 'Widen scope when local evidence points elsewhere, not merely because more code is available to read. Keep unrelated cleanup out of a focused fix.',
    remember: 'A useful hypothesis tells you what result would prove it wrong.',
  },
  'Runtime choices in context': {
    reasoning: 'Compare startup, warmup, and sustained operation separately. A runtime can start quickly yet use more CPU over a long job, or take time to optimize hot code before reaching steady performance. Choose the phase that matters to the deployment pattern rather than ranking languages with one timing number.',
    explanation: 'Runtime behavior includes startup, compilation, allocation, scheduling, libraries, and diagnostics. Managed runtimes and native code make different safety and control tradeoffs. A network-heavy API, a CPU-heavy transcoder, and a tightly bounded latency service may prioritize different properties.',
    keyPoints: ['Warmup and steady state can have different performance.', 'A runtime change cannot remove an unchanged database or network bottleneck.', 'Team expertise and operating tools influence reliability and cost.'],
    steps: ['Define the actual workload and required latency, throughput, memory, and safety properties.', 'Measure equivalent implementations with realistic I/O and data sizes.', 'Compare operational effort, failure diagnosis, and maintenance as well as benchmark speed.'],
    example: 'A rewrite makes a local serialization benchmark twice as fast, but requests still spend 90% of their time waiting on a provider. The user-visible gain is limited, and the new runtime adds operating work. Reducing provider calls or improving the interaction may address the dominant cost more directly.',
    decision: 'Use evidence to choose or tune a runtime. Avoid universal rankings based on isolated microbenchmarks or average CPU use.',
    remember: 'Choose a runtime for the whole workload, not the smallest benchmark.',
  },
  'Why system designers need a basic hardware model': {
    reasoning: 'Locality means keeping frequently related accesses close in memory or storage. Scanning an array can use caches efficiently, while following scattered pointers may spend more time fetching data. This explains why structures with similar theoretical complexity can behave differently when the working set grows beyond fast memory.',
    explanation: 'Software abstractions ultimately consume physical resources. A data structure occupies memory, a durable commit uses storage, and a remote call uses at least two machines and a network. The working set is the frequently accessed part of the data; its location strongly affects cost.',
    keyPoints: ['CPU caches, RAM, local storage, and remote storage have different access costs.', 'Sequential nearby access can outperform scattered access even with similar algorithmic complexity.', 'Resource limits and queues can matter more than raw processor speed.'],
    steps: ['Trace the resources touched by one representative request.', 'Measure which resource performs work and where the request waits.', 'Change the dominant cost and verify the complete operation under the same workload.'],
    example: 'A catalog endpoint reloads a large reference table for every request. A bounded in-memory representation may remove repeated I/O, but it must fit the working set and have a freshness policy. If the actual delay is a remote payment call, caching that unrelated table will not fix checkout latency.',
    decision: 'Use the hardware model to ask better measurement questions, not to memorize universal latency numbers. Actual devices, networks, runtimes, and workloads vary.',
    remember: 'Every abstraction has a resource cost; locate the one that limits useful work.',
  },
  'RAM, disks, and durable writes': {
    reasoning: 'A read cache and a write buffer make different promises. Losing a read cache costs performance because its source can reload the value. Losing an acknowledged write buffer can lose new information that exists nowhere else. Identify which role memory plays before deciding whether its loss is harmless.',
    explanation: 'A program may write through several buffers before bytes reach the persistence boundary it relies on. Returning from a write call is therefore not always equivalent to surviving a power or device failure. Databases coordinate logs, flushes, and sometimes replicas to make an explicit acknowledgement promise.',
    keyPoints: ['Process memory is usually lost when the process exits.', 'Operating-system and device buffers have their own persistence behavior.', 'Durability must name which failure is being survived.'],
    steps: ['Identify the accepted data and when the application reports success.', 'Follow that data through buffers, durable storage, and required replicas.', 'Crash at the acknowledgement boundary and verify recovery under the promised failure model.'],
    example: 'An upload handler reads bytes into RAM and returns complete before saving them. A restart loses an accepted upload. By contrast, a database may cache a read in RAM safely because a durable authoritative copy already exists. The same memory technology serves different roles in those two paths.',
    decision: 'Use proven storage APIs and database durability settings. Stronger persistence can add latency, so measure rather than weakening the contract silently.',
    remember: 'A durable acknowledgement is a recoverable promise, not just a successful local call.',
  },
  'Processes, threads, and isolation': {
    reasoning: 'Separate processes do not eliminate all shared state. They can still access the same files, database rows, or remote service quotas. A process-local lock protects only callers using that particular lock, so cross-process correctness must be enforced where those callers share the actual resource.',
    explanation: 'The operating system gives a process an address space and resources. Threads within it share memory while keeping their own execution state. Sharing makes communication efficient but also permits races. Separate processes improve some isolation while communicating through explicit shared resources or messages.',
    keyPoints: ['Thread safety concerns shared memory within a process.', 'Cross-process safety needs coordination at the shared resource.', 'A process crash can affect all its threads and volatile state.'],
    steps: ['Identify which state is shared by threads, processes, or machines.', 'Choose synchronization at the boundary where competing writers actually meet.', 'Test concurrent access and process replacement rather than only sequential function calls.'],
    example: 'A lock prevents two local threads from updating inventory at once. A second API process has a different lock and can still make the same conflicting decision. An atomic database reservation or supported distributed ownership protocol is required for the shared inventory rule.',
    decision: 'Use process isolation for suitable fault and security boundaries, but do not assume it isolates shared databases, disks, or downstream capacity.',
    remember: 'Protect state where it is shared, not just where one caller happens to run.',
  },
  'Garbage collection and language tradeoffs': {
    reasoning: 'An object can be useless to the business but still reachable by the program. A growing map or event-listener list can retain it indefinitely, so the collector is behaving correctly while memory use increases. Inspect who retains objects as well as how frequently collection runs.',
    explanation: 'Garbage collection reclaims unreachable objects, reducing manual memory-management errors. The runtime still pays for allocation, tracking, and reclamation. Collectors differ in pause and throughput behavior, and retained references can keep unwanted objects alive indefinitely.',
    keyPoints: ['A memory leak can be reachable data that is no longer useful.', 'Large or frequent temporary allocations can increase collection work.', 'Total process memory includes more than the managed heap.'],
    steps: ['Measure allocation rate, retained heap, process memory, and pause durations.', 'Correlate those measurements with request latency and workload changes.', 'Reduce unnecessary allocation or unbounded retention, then verify under sustained load.'],
    example: 'An image endpoint allocates several full-size buffers per request. Bursts create periodic collection pauses. Reusing suitable bounded buffers or streaming work may help more than increasing every timeout. If a downstream database is actually the wait, changing the collector will not solve it.',
    decision: 'Select runtimes using workload, safety, tooling, and team productivity. Avoid a language rewrite based only on an average CPU chart or one small benchmark.',
    remember: 'Automatic memory management removes manual cleanup work, not memory cost.',
  },
  'A realistic performance investigation': {
    reasoning: 'Match workload and measurement boundaries before comparing results. A warm-cache run with small inputs is not directly comparable to a cold-cache run with large inputs. Record those conditions so an apparent improvement can be attributed to the change rather than a cheaper test workload.',
    explanation: 'Performance investigation is a sequence of testable explanations. Start from the slow user operation, identify its time distribution, and separate execution from waiting. A focused measurement should make one explanation more or less plausible before code or infrastructure changes.',
    keyPoints: ['Use comparable healthy and failing time windows.', 'Inspect tail latency and completion rate, not only averages.', 'Correlated scheduled activity is a clue, not final proof of cause.'],
    steps: ['Describe when the slowdown occurs and which operations are affected.', 'Choose one discriminating trace, profile, query plan, or resource measurement.', 'Make a targeted change, repeat the workload, and retain a regression check.'],
    example: 'A thumbnail service slows every ten minutes. Candidate causes include allocation bursts, storage maintenance, and a scheduled export. Request traces show most time in storage waiting, while allocation remains stable. That evidence directs the next check toward I/O contention rather than a speculative garbage-collector change.',
    decision: 'Prefer a small reversible experiment with clear before-and-after evidence. Do not optimize unrelated code merely because it is easy to inspect.',
    remember: 'One good measurement should eliminate a plausible wrong explanation.',
  },
  'Data structures shape what a system can do efficiently': {
    reasoning: 'Include update cost when evaluating a read optimization. A second index may make one query faster, but every relevant insert and delete must maintain it. If the workload is mostly writes and the query is rare, the extra maintenance can cost more than the saved scans.',
    explanation: 'Structures trade one operation\'s convenience for another\'s cost. An exact-key hash lookup differs from finding a sorted range, highest-priority item, prefix match, or connected neighbor. Choosing a structure starts with the question the application repeatedly asks.',
    keyPoints: ['Big-O describes growth with input size, not a universal runtime.', 'Output size is unavoidable work even with a fast index.', 'Multiple access paths add memory and update cost.'],
    steps: ['List required reads and updates with their expected frequency and size.', 'Choose a structure or index suited to the dominant operations.', 'Measure realistic distributions, update costs, and worst important cases.'],
    example: 'A hash map quickly finds session abc but must inspect many sessions to return those created in the last hour. A time-ordered structure supports that range. Maintaining both may be worthwhile, provided updates keep both views correct or the derived view has a repair path.',
    decision: 'Use standard implementations and database indexes when appropriate. Do not build a custom search engine for a small bounded list without evidence.',
    remember: 'Efficient for one question does not mean efficient for every question.',
  },
  'Arrays, lists, stacks, and queues': {
    reasoning: 'A queue describes removal order, not a particular storage implementation. A ring buffer can support efficient bounded insertion and removal by advancing positions instead of shifting every element. The application must still decide what happens when the buffer fills, because efficient operations cannot absorb unlimited arrivals.',
    explanation: 'An array keeps indexed elements in contiguous logical positions, supporting direct access and efficient nearby reads. A linked list connects separate nodes. A stack removes the latest item first, while a queue commonly removes the oldest. Their interfaces and underlying implementations are separate choices.',
    keyPoints: ['Dynamic arrays occasionally allocate and copy during growth.', 'Linked nodes add pointer and locality costs.', 'A bounded queue needs an explicit full-capacity policy.'],
    steps: ['Choose the access order and operations the workload requires.', 'Select an implementation with suitable insertion, removal, and memory behavior.', 'Test size growth, concurrent access if needed, and overload behavior.'],
    example: 'A worker repeatedly removes the first element of a large array by shifting all remaining items. A suitable deque or ring buffer avoids that repeated linear work. However, an in-memory queue still loses pending accepted jobs on process failure unless a separate durable record exists.',
    decision: 'Prefer simple arrays for indexed or sequential data and appropriate queue structures for sustained front removal. Choose based on measured access, not familiarity alone.',
    remember: 'The data structure controls local operation cost; persistence is a separate guarantee.',
  },
  'Hash tables, sets, and trees': {
    reasoning: 'Equality and ordering must reflect the same intended identity where the application expects them to agree. Treating customer IDs as case-insensitive in one structure and case-sensitive in another can create inconsistent lookup or duplicate checks. Define normalization before evaluating the structures\' performance characteristics.',
    explanation: 'Hash tables use a hash to locate candidate buckets for exact keys and resolve collisions. Sets answer membership questions without a separate value. Ordered trees maintain key order, enabling ranges and sorted traversal. These properties explain why databases often keep more than one access path.',
    keyPoints: ['Average constant-time hashing still has collision, resize, and memory costs.', 'Tree ordering supports operations a plain hash map cannot answer cheaply.', 'Comparator and equality rules must match the application\'s identity semantics.'],
    steps: ['Define key identity and whether the query needs ordering.', 'Choose hashing, an ordered structure, or multiple deliberate indexes.', 'Benchmark lookups and updates at realistic size and skew.'],
    example: 'An invoice service needs exact invoice IDs and a time-ordered history per account. A hash map helps the first query, while an account-and-time index helps the second. Scanning the whole map for every history page would ignore the actual access pattern.',
    decision: 'Count memory and maintenance cost when adding indexes. A structure that is fast in a small in-memory test may have different locality costs at production scale.',
    remember: 'Hash for exact identity; order for ranges and traversal.',
  },
  'Bloom filters and approximate answers': {
    reasoning: 'Choose the permitted error from the business decision. An unnecessary database lookup caused by a Bloom-filter false positive may be acceptable, while charging a customer from an approximate unique-user count is not. Approximation is safe when the narrower guarantee is deliberate and exact decisions retain an authoritative path.',
    explanation: 'Approximate structures answer a limited question with much less memory than an exact dataset. Bloom filters test possible membership; HyperLogLog estimates distinct cardinality. Their error and update assumptions must fit the use case before the application relies on the result.',
    keyPoints: ['Bloom-filter positives require exact verification when correctness matters.', 'A stale filter may not contain newly inserted keys.', 'A cardinality estimate cannot identify individual members or justify exact billing.'],
    steps: ['Choose the precise question and acceptable error model.', 'Build and update the proven structure with consistent identities and configuration.', 'Compare with exact samples and handle lag, rebuild, and unsupported operations deliberately.'],
    example: 'A dashboard estimates unique visitors with a small sketch while a storage engine uses Bloom filters to avoid unnecessary file reads. Neither can replace an authoritative order ledger. The dashboard tolerates estimation error; the storage engine verifies possible matches and uses filters representing the actual file contents.',
    decision: 'Use approximation to save measurable resources where uncertainty is acceptable. Keep exact checks at business decisions requiring exact identity or counts.',
    remember: 'A smaller structure is useful because it promises a narrower answer.',
  },
  'Indexes, search, and time-series organization': {
    reasoning: 'Time partitioning helps only when queries can eliminate irrelevant time ranges. A query without a time constraint may still inspect many partitions. Choose retention and partition size with both common queries and delayed events in mind, so old but legitimate input has a defined destination or rejection policy.',
    explanation: 'An index arranges data for a chosen lookup pattern. An inverted index maps terms to documents, while time-based organization groups records by timestamp and often another key. Partitioning by time can also make retention and bounded scans easier to manage.',
    keyPoints: ['Choose key order from the filters and ordering used together.', 'Search ranking and exact record lookup are different workloads.', 'Retention and late-arriving events affect time-partitioned data.'],
    steps: ['Identify the common query range, filters, and maximum returned size.', 'Build the matching index or time partition strategy.', 'Measure scanned data, update overhead, and behavior for late or corrected records.'],
    example: 'A monitoring page requests the latest hour for one service but scans years of logs. Time partition pruning and a suitable service/time index reduce work. A late log event may belong to an older partition, so ingestion and retention must agree on how to handle it.',
    decision: 'Avoid indexing every field without query evidence. Each index consumes storage and update work, and large outputs remain expensive to transfer.',
    remember: 'An index saves work when its organization matches the actual query.',
  },
  'A worked example: product autocomplete': {
    reasoning: 'Client-side debouncing can reduce queries while a person types, but it does not replace server-side limits. Several slow responses may also arrive out of order. Associate results with the current query so a late response for an older prefix does not overwrite newer suggestions.',
    explanation: 'Autocomplete is a bounded candidate-retrieval problem with a latency budget. A small catalog can use an indexed prefix query. Larger catalogs may need language analysis, typo tolerance, popularity ranking, and a dedicated derived search index.',
    keyPoints: ['Return a small useful candidate set rather than every prefix match.', 'Normalize text consistently with the chosen language behavior.', 'Current availability and authorization remain separate from suggestion ranking.'],
    steps: ['Choose matching and ranking requirements from the user experience.', 'Maintain an index with stable source IDs, versions, and deletion handling.', 'Serve bounded suggestions and verify current records before important actions.'],
    example: 'A shopper types lap and receives ranked laptop suggestions. A delayed product deletion must not be undone by an older index update. Version checks keep the derived index coherent, while checkout still confirms that the selected product exists and can be purchased.',
    decision: 'Start with a database index when it meets scale and relevance needs. Add specialized search only when its features and operating cost are justified.',
    remember: 'Autocomplete suggests candidates quickly; it does not accept the final business action.',
  },
  'Threads, tasks, and event loops': {
    reasoning: 'A task waiting on I/O can release execution resources without releasing every other resource it holds. It might still occupy a database connection, buffer, or lock. Bound those resources explicitly; many cheap-to-schedule tasks can collectively overload a dependency even when thread count remains small.',
    explanation: 'A thread is a scheduled execution path; a task or promise represents work that may execute on a thread pool or event loop. Async I/O allows a thread to do other work while an operation waits. CPU-heavy code still occupies execution time even inside an async function.',
    keyPoints: ['Concurrency does not require a dedicated thread per task.', 'Blocking an event loop delays unrelated tasks using that loop.', 'Worker pools and task queues need bounds.'],
    steps: ['Separate operations that wait on I/O from those that compute heavily.', 'Use the runtime\'s async facilities and bounded workers appropriately.', 'Measure event-loop delay, thread saturation, queued work, and downstream capacity.'],
    example: 'A request handler awaits a database call, then compresses a large image synchronously. The I/O is nonblocking, but image processing still blocks other work on the same event loop. Moving that computation to a bounded worker pool can help without launching unlimited parallel tasks.',
    decision: 'Use the runtime\'s documented model rather than assuming async means parallel or thread-safe. Keep cancellation and resource cleanup explicit.',
    remember: 'Async manages waiting; parallel execution needs actual execution resources.',
  },
  'Race conditions and atomic operations': {
    reasoning: 'Check both final state and accepted responses when testing a race. Two buyers can both receive success while a lost update leaves stored stock at zero rather than negative. The final number looks valid, but the system sold two items. Assert the business invariant across all accepted operations.',
    explanation: 'A race condition makes a result depend incorrectly on the timing of overlapping operations. An atomic operation combines the relevant decision and change so competing callers cannot interleave inside that protected boundary. The boundary must include every writer that can violate the rule.',
    keyPoints: ['Read-then-write is not automatically atomic.', 'A local mutex does not coordinate unrelated processes.', 'Some invariants span multiple records and need a broader transaction.'],
    steps: ['State the invariant and identify all concurrent writers.', 'Use a conditional update, constraint, lock, or transaction at the shared owner.', 'Test conflicting operations simultaneously and assert accepted outcomes, not just final logs.'],
    example: 'Two buyers read remaining stock as one. Each subtracts one locally and writes zero, so the final value looks reasonable even though two purchases were accepted. A stored conditional decrement permits only one success and gives the other caller a clear out-of-stock result.',
    decision: 'Protect the business decision, not merely one assignment in code. Tests should check promises made to callers as well as the final stored value.',
    remember: 'Atomicity must cover the check and the change at the real shared boundary.',
  },
  'Deadlocks, starvation, and bounded resources': {
    reasoning: 'Consistent lock ordering prevents many waiting cycles, but it does not ensure fairness. A high-priority stream of work can repeatedly delay other eligible tasks without any deadlock. Observe waiting time by workload class and choose scheduling or admission policies that let the intended users make progress.',
    explanation: 'Deadlock is a waiting cycle: each participant holds something another needs. Starvation means work repeatedly loses access even without a cycle. Resource bounds, fair scheduling, consistent lock order, and safe retry policies address different parts of these problems.',
    keyPoints: ['Longer timeouts do not remove a dependency cycle.', 'Database deadlock detection may abort one participant.', 'Holding locks during slow external calls increases contention risk.'],
    steps: ['Map resources acquired by overlapping operations and their order.', 'Use a consistent acquisition strategy and keep protected sections bounded.', 'Handle aborts with safe retries and measure whether all eligible work can make progress.'],
    example: 'A transfer locks account A then B, while another locks B then A. Each waits for the other. Ordering account locks consistently removes this cycle. If the database aborts a transaction, retrying must preserve the transfer identity and not repeat an already accepted external action.',
    decision: 'Distinguish deadlock from simple saturation or a slow dependency. Choose the remedy from evidence about what each task is waiting for.',
    remember: 'Prevent waiting cycles and give competing work a bounded path to progress.',
  },
  'Structured cancellation and deadlines': {
    reasoning: 'Cleanup should run even when work is cancelled. Releasing connections and stopping owned subtasks prevents abandoned requests from consuming capacity indefinitely. However, cleanup must not erase the only record of an uncertain external effect; retain its identity so a separate recovery path can discover the final outcome.',
    explanation: 'A deadline limits how long an operation remains useful. Structured cancellation propagates a request to stop related work and release resources. Cancellation is cooperative and does not prove that remote work or a business side effect never happened.',
    keyPoints: ['Pass the remaining deadline rather than restarting a full timeout at every hop.', 'Clean up resources even when the caller stops waiting.', 'Reconcile uncertain external effects using their original identities.'],
    steps: ['Set an end-to-end budget from the user workflow.', 'Propagate cancellation and remaining time through owned subtasks.', 'Record or recover any effect that may have crossed a commit boundary before cancellation.'],
    example: 'A user closes checkout just after the payment provider accepts the charge. Cancelling the browser request cannot reverse that charge. The backend retains the payment ID and reconciles whether the order should complete or be refunded, rather than treating the vanished caller as proof of no payment.',
    decision: 'Use cancellation to stop wasted local work, but model irreversible or independently committed effects explicitly.',
    remember: 'Stopping the wait is not the same as undoing the work.',
  },
  'A worked example: generating invoices': {
    reasoning: 'An invoice run needs stable occurrence keys such as customer plus billing period. A process ID changes after restart and cannot identify work already completed by an earlier worker. Store each accepted result under its business occurrence so resuming a partial run skips finished work without skipping unfinished customers.',
    explanation: 'Invoice generation illustrates why useful concurrency is bounded by dependencies. Running everything sequentially may waste available capacity, while launching every task at once can exhaust database connections, memory, or provider quotas. Durable progress separates the workload from individual workers.',
    keyPoints: ['Choose worker concurrency from measured downstream limits.', 'Give each invoice occurrence a stable business identity.', 'Keep completed and pending work recoverable across restarts.'],
    steps: ['Persist the requested invoice set and its occurrence keys.', 'Process a bounded batch with controlled database and provider concurrency.', 'Record each result before advancing progress, then retry only unfinished or uncertain work safely.'],
    example: 'A monthly run needs 1,000 invoices. Twenty workers may keep the database busy without overwhelming it, while 1,000 simultaneous tasks mostly wait for connections. If a worker restarts after saving invoice 417, its stable key lets the resumed run recognize that completed result.',
    decision: 'Tune from sustained completion and queue age rather than CPU alone. Isolate large batch work from latency-sensitive customer requests where necessary.',
    remember: 'The right concurrency is enough to use capacity, not enough to exhaust every resource.',
  },
  'Layers separate real responsibilities': {
    reasoning: 'Translate infrastructure failures without losing their meaning. A persistence adapter may report a version conflict, unavailable database, or unknown commit outcome. The business layer needs these distinctions to choose between asking the user to reconcile, retrying later, and checking the original operation before attempting another change.',
    explanation: 'Presentation interprets user input and displays results. Domain logic owns business rules. Persistence manages stored records, and integration code communicates with external systems. Separating these responsibilities helps reuse rules across clients and makes failures easier to test.',
    keyPoints: ['A screen controller should not be the only authority for a shared rule.', 'Dependencies should expose useful behavior rather than leaking every storage detail.', 'Layering is valuable when it reduces coupling, not merely when folders look tidy.'],
    steps: ['Identify the owner of each decision and the data it needs.', 'Place authoritative rules in operations shared by all relevant callers.', 'Test the rule independently, then verify the real storage and external boundaries.'],
    example: 'A web page prevents a discount above 20%, but a mobile client calls the API directly. If the backend trusts the supplied discount, the screen rule is bypassed. A domain pricing operation validates the discount for every client, while each screen retains helpful local validation.',
    decision: 'Keep layers proportionate to complexity. An extra pass-through abstraction adds little if it neither protects a contract nor simplifies change.',
    remember: 'Put a rule where every caller must pass through its authority.',
  },
  'Bounded contexts and data ownership': {
    reasoning: 'Translation between contexts prevents one team\'s internal representation from becoming everyone\'s shared dependency. Billing may need a verified payer ID rather than the entire marketing profile. Expose the minimum meaningful fact, and version that contract so internal field changes do not silently alter another context\'s decisions.',
    explanation: 'A bounded context defines a business model with consistent meaning inside one area. The same word can represent different facts elsewhere. Explicit translation and ownership keep one team\'s model change from silently rewriting another team\'s assumptions.',
    keyPoints: ['Marketing\'s customer may be a prospect; billing\'s customer may be a verified payer.', 'Sharing an identifier does not grant shared write authority over every fact.', 'Contracts should communicate the facts another context actually needs.'],
    steps: ['Define the meaning and owner of important business terms.', 'Keep internal models focused on their context\'s operations.', 'Translate through supported APIs or events and test changes at those boundaries.'],
    example: 'Marketing marks an email lead as active, while billing treats active customer as an approved payer. Reusing one global boolean lets a marketing action accidentally enable billing. Separate models and an explicit verification event preserve each meaning without forcing both teams to share every field.',
    decision: 'A bounded context need not become a separate deployed service immediately. First establish the model and ownership; deployment follows actual operating needs.',
    remember: 'A shared word is not necessarily a shared business fact.',
  },
  'Client patterns: MVC, MVP, and MVVM': {
    reasoning: 'Represent mutually exclusive screen states explicitly, such as idle, loading, loaded, and failed. Independent flags can accidentally show loading and success together. A controller, presenter, or view model can own those transitions while the server separately owns whether the requested business operation was actually accepted.',
    explanation: 'These patterns organize presentation responsibilities. MVC separates model, view, and controller. MVP puts view coordination in a presenter. MVVM exposes presentation state and commands through a view model, often with binding. Framework conventions influence their exact shape.',
    keyPoints: ['Presentation state includes loading, validation, retry, and selection.', 'A client model is not automatically the authoritative server record.', 'The pattern should make screen behavior easier to test and change.'],
    steps: ['Identify UI state and events separately from server-side business rules.', 'Choose the framework-supported coordinator or state model for those interactions.', 'Test success, loading, error, cancellation, and retry states without relying only on manual clicks.'],
    example: 'Several controls independently implement report loading and error handling, producing inconsistent screen states. A shared view model or presenter owns one report-request state and exposes commands. The backend still authorizes the report and controls durable completion regardless of the chosen presentation pattern.',
    decision: 'Follow the existing client framework rather than forcing textbook terminology onto every component. Keep authoritative rules outside client-only checks.',
    remember: 'Presentation patterns organize interaction, not backend authority or deployment.',
  },
  'A learning-platform example': {
    reasoning: 'Enrollment, payment, and media readiness should not share one ambiguous completed flag. A student may own access while a newly uploaded lesson is still processing. Separate states let the interface explain the situation honestly and let workers retry media processing without recreating payment or enrollment.',
    explanation: 'A learning platform connects accounts, content, enrollment, billing, and media processing. These capabilities can begin as clear modules in one application. Different workloads, such as video transcoding and reading course text, can use different execution resources without requiring every module to become a service.',
    keyPoints: ['Enrollment and access rules belong to an authoritative owner.', 'Large media bytes fit object storage and eligible CDN delivery.', 'Slow processing should have durable jobs and visible states.'],
    steps: ['Define purchase, enrollment, viewing, and upload outcomes and permissions.', 'Implement a complete simple path with durable records and bounded media workers.', 'Extract independently operated capabilities only when scale or team ownership justifies it.'],
    example: 'A paid enrollment is accepted while video processing is still running. The course can show a truthful processing state instead of claiming the video is playable. Once all required outputs are verified, publication makes them available through authorized delivery. Billing retries keep the same payment identity.',
    decision: 'A modular monolith can serve the initial product well. Invest first in clear state transitions and recovery rather than service count.',
    remember: 'Different workloads need clear responsibilities, not automatically different network services.',
  },
}